### PR TITLE
Add database check

### PR DESCRIPTION
**Pull request by odnobit**
## Context

Add database check

## Description

Implemented database checking in /health handler for enhanced system monitoring.

### CODE REVIEW

**Review by jdenquin — CHANGES_REQUESTED** [review]
Nice! Would be nice to add a rescue and return an error if the database is not working!

**Comment by odnobit** [comment]
Changes have been updated. Thanks for the comment!

**Review by jdenquin — COMMENTED** [review]
if you can just check the indentation, all good for me!

**Comment by odnobit** [comment]
> if you can just check the indentation, all good for me!

I'm sorry, I didn't understand the linter's message. There's nothing about indentation in it
```
/opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/git/repository.rb:99:in `merge_base': object not found - no match for id (d8d6c5baf1b4ce9bde6209d7e204be68ea3f3a96) (Rugged::OdbError)
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/git/repository.rb:99:in `merge_base'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/git/repository.rb:29:in `diff'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto.rb:64:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/cli.rb:70:in `block in run'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `chdir'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/lib/pronto/cli.rb:68:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/pronto-0.11.2/bin/pronto:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/bin/pronto:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.2.2/x64/bin/pronto:25:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by jdenquin** [comment]
No worries with the Linter, it's not working when it has to lint a fork (I have to fix it)

**Comment by odnobit** [comment]
> No worries about the Linter, it's not working when it has to lint a fork (I have to fix it)

okay, will fix the indents tonight, thx

**Review by jdenquin — APPROVED** [review]

**Pull request merged**
